### ISSUE TITLE
Cornify does http errors

### ISSUE THREAD

**Issue by dragonito** [tolry/bcr#3]
:/ its broken

**Comment by tolry** [comment]
fix it? :wink: don't know when I will have the time to take a look at this, sorry, after the holidays probably - if it's urgent, go ahead and debug/fix it yourself. I will merge quickly, if you have a fix.

**Comment by tolry** [comment]
btw: problem seems to be cornifies expired (5th Dec 2018)  https certificate -> https://www.cornify.com/

**Comment by tolry** [comment]
certificate was renewed some time ago
